/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed": "#261900",
          "primary-fixed": "#ffdea5",
          "tertiary-container": "#9fa4bc",
          "on-background": "#d4e4fa",
          "inverse-surface": "#d4e4fa",
          "outline": "#9a8f80",
          "background": "#051424",
          "surface-container-lowest": "#010f1f",
          "on-secondary-fixed": "#0d1c32",
          "on-surface": "#d4e4fa",
          "error": "#ffb4ab",
          "on-primary": "#412d00",
          "on-tertiary": "#2a3043",
          "on-error": "#690005",
          "secondary-container": "#3c4962",
          "inverse-primary": "#775a19",
          "on-tertiary-fixed-variant": "#40465a",
          "on-error-container": "#ffdad6",
          "on-secondary-container": "#abb9d6",
          "inverse-on-surface": "#233143",
          "tertiary": "#c0c6de",
          "error-container": "#93000a",
          "on-tertiary-fixed": "#151b2d",
          "secondary": "#b9c7e4",
          "on-primary-container": "#4e3700",
          "on-secondary-fixed-variant": "#39475f",
          "surface-variant": "#273647",
          "surface-bright": "#2c3a4c",
          "on-primary-fixed-variant": "#5d4201",
          "tertiary-fixed": "#dce1fb",
          "primary-container": "#c5a059",
          "tertiary-fixed-dim": "#c0c6de",
          "outline-variant": "#4e4639",
          "primary": "#e9c176",
          "on-surface-variant": "#d1c5b4",
          "primary-fixed-dim": "#e9c176",
          "surface-dim": "#051424",
          "secondary-fixed": "#d6e3ff",
          "on-secondary": "#233148",
          "surface-container-highest": "#273647",
          "surface": "#051424",
          "secondary-fixed-dim": "#b9c7e4",
          "surface-container": "#122131",
          "on-tertiary-container": "#343a4e",
          "surface-tint": "#e9c176",
          "surface-container-high": "#1c2b3c",
          "surface-container-low": "#0d1c2d"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "lg": "40px",
          "container-max": "1440px",
          "base": "8px",
          "sm": "12px",
          "sidebar-width": "280px",
          "xs": "4px",
          "md": "24px",
          "xl": "64px"
      },
      "fontFamily": {
          "sans": ["Inter", "sans-serif"],
          "serif": ["Newsreader", "serif"],
          "display-md": ["Newsreader"],
          "table-data": ["Inter"],
          "body-lg": ["Inter"],
          "body-sm": ["Inter"],
          "headline-sm": ["Newsreader"],
          "display-lg": ["Newsreader"],
          "body-md": ["Inter"],
          "label-caps": ["Inter"]
      },
      "fontSize": {
          "display-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500"}],
          "table-data": ["14px", {"lineHeight": "1.4", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
          "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
